#!/usr/bin/env python
# vim:ft=python

def main(*args):
    if len(args) == 1:
        filename = args[0]
    else:
        print "Usage <file>"%(sys.argv[0])
        sys.exit(1)

    i = 0
    for line in open(filename).readlines():
        print i, line,
        i += 1

if __name__ == "__main__":
    import sys
    main(*sys.argv[1:])
